# Generated by Django 4.0.1 on 2022-01-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='title',
            field=models.CharField(default='x', max_length=100),
        ),
    ]
