# Generated by Django 4.0.1 on 2022-02-02 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_jobs_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 2, 2)),
        ),
    ]
