# Generated by Django 4.0.1 on 2022-02-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_jobs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='date',
            field=models.CharField(default='x', max_length=100),
        ),
    ]
