# Generated by Django 4.0.1 on 2022-02-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_alter_jobs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
