# Generated by Django 4.0.1 on 2022-02-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_alter_jobs_iscomp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='iscomp',
            field=models.BooleanField(default='False', max_length='10'),
        ),
    ]
