# Generated by Django 4.0.1 on 2022-02-07 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_alter_jobs_iscomp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='iscomp',
        ),
    ]
