# Generated by Django 4.0.1 on 2022-02-07 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0013_alter_jobs_iscomp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='iscomp',
            new_name='comp',
        ),
    ]
