# Generated by Django 4.0.1 on 2022-02-07 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0016_jobs_comp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='comp',
            new_name='x',
        ),
    ]
