# Generated by Django 4.0.1 on 2022-02-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0017_rename_comp_jobs_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='x',
            field=models.CharField(default='', max_length=100),
        ),
    ]
