# Generated by Django 4.0.1 on 2022-02-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0019_remove_jobs_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='comp',
            field=models.CharField(default='', max_length=100),
        ),
    ]
