# Generated by Django 4.0.1 on 2022-02-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0023_alter_jobs_comp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='comp',
        ),
    ]
