# Generated by Django 4.0.1 on 2022-02-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0025_jobs_comp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='comp',
            field=models.CharField(default='false', max_length=100),
        ),
    ]
